import { lessonStatuses, ModuleCardType } from "@/shared/components/module-card/types";

export const constants = {
  mockModules: [
    {
      id: '1',
      title: 'Введение',
      module_number: 1,
      description:
        'Узнайте, как будет построен курс: какие форматы занятий вас ждут и как они помогут пройти собеседование. Определим цели, разберём частые ошибки и начнём строить индивидуальную стратегию подготовки.',
      lessons: [
        {
          id: 'l1',
          name: 'Урок 1',
          status: lessonStatuses.VERIFIED,
          stars: 3,
          total_stars: 3,
          tasks: [
            { id: 't1', name: 'Задача 1', stars: 0, total_stars: 3 },
            { id: 't2', name: 'Задача 2', stars: 0, total_stars: 3 },
          ],
        },
        {
          id: 'l2',
          name: 'Урок 2',
          status: lessonStatuses.ACTIVE,
          stars: 0,
          total_stars: 3,
          tasks: [{ id: 't3', name: 'Задача 3', stars: 0, total_stars: 3 }],
        },
        {
          id: 'l3',
          name: 'Урок 3',
          status: lessonStatuses.BLOCKED,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
      ],
      status: {
        state: 'completed',
        progress: '50',
        total_stars: 9,
      },
      total_tasks: 10,
      img_url: '/images/astronaut1.webp',
      bonus: false,
    },
    {
      id: '2',
      title: 'Анализ',
      module_number: 2,
      description:
        'Разберём ваш профессиональный путь: от навыков и опыта до достижений. Вы поймёте, как сформулировать свои сильные стороны, на чём сделать акцент в резюме и как преподнести себя.',
      lessons: [
        {
          id: 'l4',
          name: 'Урок 4',
          status: lessonStatuses.VERIFIED,
          stars: 3,
          total_stars: 3,
          tasks: [],
        },
        {
          id: 'l5',
          name: 'Урок 5',
          status: lessonStatuses.ACTIVE,
          stars: 3,
          total_stars: 3,
          tasks: [],
        },
        {
          id: 'l6',
          name: 'Урок 6',
          status: lessonStatuses.BLOCKED,
          stars: 3,
          total_stars: 3,
          tasks: [],
        },
        {
          id: 'l7',
          name: 'Урок 7',
          status: lessonStatuses.BLOCKED,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
        {
          id: 'l8',
          name: 'Урок 8',
          status: lessonStatuses.BLOCKED,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
      ],
      status: {
        state: 'active',
        progress: '15',
        total_stars: 15,
      },
      total_tasks: 15,
      img_url: '/images/astronaut2.webp',
      bonus: false,
    },
    {
      id: 'bonus-1',
      title: 'Бонусный модуль',
      module_number: 0,
      description:
        'В этом модуле вы научитесь составлять сильное, структурированное резюме под конкретные вакансии. Разберём, как выделить ключевые навыки, грамотно описать опыт и избежать типичных ошибок.',
      lessons: [
        {
          id: 'l9',
          name: 'Бонус урок 1',
          status: lessonStatuses.ACTIVE,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
        {
          id: 'l10',
          name: 'Бонус урок 2',
          status: lessonStatuses.BLOCKED,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
      ],
      status: {
        state: 'blocked',
        progress: null,
        total_stars: null,
      },
      total_tasks: 5,
      img_url: '/images/astronaut3.webp',
      bonus: true,
    },
    {
      id: '4',
      title: 'Введение в React',
      module_number: 1,
      description:
        'Узнайте, как будет построен курс: какие форматы занятий вас ждут и как они помогут пройти собеседование. Определим цели, разберём частые ошибки и начнём строить индивидуальную стратегию подготовки.',
      lessons: [
        {
          id: 'l1',
          name: 'Урок 1',
          status: lessonStatuses.VERIFIED,
          stars: 3,
          total_stars: 3,
          tasks: [
            { id: 't1', name: 'Задача 1', stars: 0, total_stars: 3 },
            { id: 't2', name: 'Задача 2', stars: 0, total_stars: 3 },
          ],
        },
        {
          id: 'l2',
          name: 'Урок 2',
          status: lessonStatuses.ACTIVE,
          stars: 0,
          total_stars: 3,
          tasks: [{ id: 't3', name: 'Задача 3', stars: 0, total_stars: 3 }],
        },
        {
          id: 'l3',
          name: 'Урок 3',
          status: lessonStatuses.BLOCKED,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
      ],
      status: {
        state: 'blocked',
        progress: '50',
        total_stars: 9,
      },
      total_tasks: 10,
      img_url: '/images/astronaut1.webp',
      bonus: false,
    },
    {
      id: '1',
      title: 'Введение',
      module_number: 1,
      description:
        'Узнайте, как будет построен курс: какие форматы занятий вас ждут и как они помогут пройти собеседование. Определим цели, разберём частые ошибки и начнём строить индивидуальную стратегию подготовки.',
      lessons: [
        {
          id: 'l1',
          name: 'Урок 1',
          status: lessonStatuses.VERIFIED,
          stars: 3,
          total_stars: 3,
          tasks: [
            { id: 't1', name: 'Задача 1', stars: 0, total_stars: 3 },
            { id: 't2', name: 'Задача 2', stars: 0, total_stars: 3 },
          ],
        },
        {
          id: 'l2',
          name: 'Урок 2',
          status: lessonStatuses.ACTIVE,
          stars: 0,
          total_stars: 3,
          tasks: [{ id: 't3', name: 'Задача 3', stars: 0, total_stars: 3 }],
        },
        {
          id: 'l3',
          name: 'Урок 3',
          status: lessonStatuses.BLOCKED,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
      ],
      status: {
        state: 'blocked',
        progress: '50',
        total_stars: 9,
      },
      total_tasks: 10,
      img_url: '/images/astronaut1.webp',
      bonus: false,
    },
    {
      id: '2',
      title: 'Анализ',
      module_number: 2,
      description:
        'Разберём ваш профессиональный путь: от навыков и опыта до достижений. Вы поймёте, как сформулировать свои сильные стороны, на чём сделать акцент в резюме и как преподнести себя.',
      lessons: [
        {
          id: 'l4',
          name: 'Урок 4',
          status: lessonStatuses.VERIFIED,
          stars: 3,
          total_stars: 3,
          tasks: [],
        },
        {
          id: 'l5',
          name: 'Урок 5',
          status: lessonStatuses.VERIFIED,
          stars: 3,
          total_stars: 3,
          tasks: [],
        },
        {
          id: 'l6',
          name: 'Урок 6',
          status: lessonStatuses.ACTIVE,
          stars: 3,
          total_stars: 3,
          tasks: [],
        },
        {
          id: 'l7',
          name: 'Урок 7',
          status: lessonStatuses.BLOCKED,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
        {
          id: 'l8',
          name: 'Урок 8',
          status: lessonStatuses.BLOCKED,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
      ],
      status: {
        state: 'blocked',
        progress: '15',
        total_stars: 15,
      },
      total_tasks: 15,
      img_url: '/images/astronaut2.webp',
      bonus: false,
    },
    {
      id: 'bonus-1',
      title: 'Бонусный модуль',
      module_number: 0,
      description:
        'В этом модуле вы научитесь составлять сильное, структурированное резюме под конкретные вакансии. Разберём, как выделить ключевые навыки, грамотно описать опыт и избежать типичных ошибок.',
      lessons: [
        {
          id: 'l9',
          name: 'Бонус урок 1',
          status: lessonStatuses.ACTIVE,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
        {
          id: 'l10',
          name: 'Бонус урок 2',
          status: lessonStatuses.BLOCKED,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
      ],
      status: {
        state: 'blocked',
        progress: null,
        total_stars: null,
      },
      total_tasks: 5,
      img_url: '/images/astronaut3.webp',
      bonus: true,
    },
    {
      id: '4',
      title: 'Введение в React',
      module_number: 1,
      description:
        'Узнайте, как будет построен курс: какие форматы занятий вас ждут и как они помогут пройти собеседование. Определим цели, разберём частые ошибки и начнём строить индивидуальную стратегию подготовки.',
      lessons: [
        {
          id: 'l1',
          name: 'Урок 1',
          status: lessonStatuses.VERIFIED,
          stars: 3,
          total_stars: 3,
          tasks: [
            { id: 't1', name: 'Задача 1', stars: 0, total_stars: 3 },
            { id: 't2', name: 'Задача 2', stars: 0, total_stars: 3 },
          ],
        },
        {
          id: 'l2',
          name: 'Урок 2',
          status: lessonStatuses.ACTIVE,
          stars: 0,
          total_stars: 3,
          tasks: [{ id: 't3', name: 'Задача 3', stars: 0, total_stars: 3 }],
        },
        {
          id: 'l3',
          name: 'Урок 3',
          status: lessonStatuses.BLOCKED,
          stars: 0,
          total_stars: 3,
          tasks: [],
        },
      ],
      status: {
        state: 'blocked',
        progress: '50',
        total_stars: 9,
      },
      total_tasks: 10,
      img_url: '/images/astronaut1.webp',
      bonus: false,
    },
  ] as ModuleCardType[],
};