export enum ROUTES {
  LANDING_PAGE = '/',
  LOGIN_PAGE = '/login',
  REGISTER_PAGE = '/register',
  FORGOT_PASSWORD = '/forgotPassword',
  RESET_PASSWORD = '/resetPassword',
  USER_AGREEMENT = 'user-agreement',
  PRIVACY_POLICY = 'privacy-policy',
  USER_HOME_PAGE = '/learn',
  USER_EXAMS = '/learn/exams',
  USER_KNOWLEDGE_BASE = '/learn/knowledgeBase',
  USER_AI_ASSISTANT = '/learn/aiAssistant',
  USER_FREQUENTLY_ASKED_QUESTIONS = 'user-frequently-asked-questions',
  USER_MODULES = '/learn/modules',
  USER_PROJECTS = '/learn/projects',
  USER_PROFILE_PERSONAL_DATA = '/learn/userProfile/personalData',
  USER_PROFILE_SECURITY_SETTINGS = '/learn/userProfile/securitySettings',
  USER_INTERVIEW_QUESTIONS = 'user-interview-questions',
  USER_INTERVIEW_RECORDS = 'user-interview-records',
  MENTOR_STUDENTS = '/mentor/students',
  MENTOR_MODULES = '/mentor/modules',
  MENTOR_COURSES = '/mentor/courses',
}
