export enum ROUTES {
  LANDING_PAGE = '/',
  LOGIN_PAGE = '/login',
  REGISTER_PAGE = '/register',
  FORGOT_PASSWORD = '/forgot-password',
  RESET_PASSWORD = '/reset-password',
  USER_AGREEMENT = '/user-agreement',
  PRIVACY_POLICY = '/privacy-policy',
  USER_HOME_PAGE = '/learn',
  USER_EXAMS = '/learn/exams',
  USER_KNOWLEDGE_BASE = '/learn/knowledge-base',
  USER_AI_ASSISTANT = '/learn/ai-assistant',
  USER_FREQUENTLY_ASKED_QUESTIONS = 'user-frequently-asked-questions',
  USER_MODULES = '/learn/modules',
  USER_COURSES = '/learn/courses',
  USER_PROJECTS = '/learn/projects',
  USER_PROFILE_PERSONAL_DATA = '/learn/user-profile/personal-data',
  USER_PROFILE_SECURITY_SETTINGS = '/learn/user-profile/security-settings',
  USER_INTERVIEW_QUESTIONS = 'user-interview-questions',
  USER_INTERVIEW_RECORDS = 'user-interview-records',
  MENTOR_STUDENTS = '/mentor/students',
  MENTOR_MODULES = '/mentor/modules',
  MENTOR_COURSES = '/mentor/courses',
}
