export const constants = {
  statuses: {
    COMPLETED: 'PROGRESS_STATUSES.COMPLETED',
    NOT_STARTED: 'PROGRESS_STATUSES.NOT_STARTED',
    BLOCKED: 'PROGRESS_STATUSES.BLOCKED',
    IN_PROGRESS: 'PROGRESS_STATUSES.IN_PROGRESS',
  },
};
